version: "3"
services:
  database-postgres:
    container_name: postgres
    image: postgres:12.6
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: recipedb

