version: "3"
services:
  database-postgres:
    container_name: postgres
    image: postgres:12.6
    ports:
      - "5432:5432"
    volumes:
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: recipedb
